# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='ingrese pregunta'),
        ),
    ]
