# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180316_1233'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='choice',
            managers=[
            ],
        ),
    ]
